### ISSUE TITLE
Disabling Extensions

### ISSUE THREAD

**Issue by bishbashbackup** [ocfl-archive/gocfl#146]
Hiya,

I've only recently come across OCFL and have no prior experience with Golang. So, apologies in advance for any ignorance my part, but I'm keen to learn. :) I'm using Ubuntu 22.04.5 LTS, and have installed gocfl via the go ecosystem. However, I've encountered a couple of issues, which I'm hoping to get advice on:

1. Is there a  way for me to choose which community/local OCFL extensions GOCFL uses? I'd like to not use any extensions initially, to keep things as simple as possible, then possibly add them in future.

2. I've been able to init a new OCFL structure. But when I try to add files to that structure, I'm getting the error below:

> alex.habgood@ow-archive3-l:~$` gocfl add '/home/alex.habgood/Documents/gocfl test/ocfl_package' '/home/alex.habgood/Documents/gocfl test/v1' --object-id v1
> 
> opening '/home/alex.habgood/Documents/gocfl test/ocfl_package'
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xdd9a69]
> 
> goroutine 1 [running]:
> github.com/ocfl-archive/gocfl/v2/pkg/ocfl.(*ExtensionFactory).CreateExtensions(0xc0004165f0, {0x18ebcc0, 0xc0006baac0}, {0x0, 0x0})
> 	/home/alex.habgood/go/pkg/mod/github.com/ocfl-archive/gocfl/v2@v2.0.5/pkg/ocfl/extensionFactory.go:97 +0x229
> github.com/ocfl-archive/gocfl/v2/pkg/ocfl.LoadStorageRoot({0x18fa9d0, 0xc001b505a0}, {0x18ebcc0, 0xc000651d20}, 0xc0004165f0, {0x1903260, 0xc0006fc150})
> 	/home/alex.habgood/go/pkg/mod/github.com/ocfl-archive/gocfl/v2@v2.0.5/pkg/ocfl/storageroot.go:116 +0x2c5
> github.com/ocfl-archive/gocfl/v2/gocfl/cmd.doAdd(0x2aca5e0, {0xc000b15040, 0x2, 0x134e3e4?})
> 	/home/alex.habgood/go/pkg/mod/github.com/ocfl-archive/gocfl/v2@v2.0.5/gocfl/cmd/add.go:264 +0x1a0b
> github.com/spf13/cobra.(*Command).execute(0x2aca5e0, {0xc000b15000, 0x4, 0x4})
> 	/home/alex.habgood/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
> github.com/spf13/cobra.(*Command).ExecuteC(0x2acaba0)
> 	/home/alex.habgood/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/alex.habgood/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
> github.com/ocfl-archive/gocfl/v2/gocfl/cmd.Execute()
> 	/home/alex.habgood/go/pkg/mod/github.com/ocfl-archive/gocfl/v2@v2.0.5/gocfl/cmd/root.go:230 +0x1a
> main.main()
> 	/home/alex.habgood/go/pkg/mod/github.com/ocfl-archive/gocfl/v2@v2.0.5/gocfl/main.go:16 +0xf

Am hoping this can be resolved by editing the config toml file. However, I'm not sure what I'd need to do in that regard. Any advice would be greatly appreciated. Let me know if any more information is needed.

Thanks in advance,
Alex

**Comment by ross-spencer** [comment]
hi @bishbashbackup great to hear you're interested in this project.

It can be a little tricky to get up to speed at first, there's definitely a little work to keep improving documentation, which we're in progress of but anything you find that can help is appreciated. Also, that being said, it sounds like you've made a good start!

WRT to starting with a pretty vanilla install, your default toml should have these lines commented out, which means you won't be using any additional extensions:

https://github.com/ocfl-archive/gocfl/blob/eb4a7c86f6aa461052adfb4e04e9390d19da5307/config/default.toml#L28-L34

https://github.com/ocfl-archive/gocfl/blob/eb4a7c86f6aa461052adfb4e04e9390d19da5307/config/default.toml#L43-L44

If that's not the case, then please do just comment those out.

Have you any further info on the version you're using?

My dev version string currently looks like this, but yours might have more info:

```
$ ./gocfl --version
gocfl version dev-0.0.0 '000000' (1970-01-01T00:00:01Z)
```

Failing that, a commit hash from git would be super!

RE: your add command, it looks similar to one of mine:

```bash
./gocfl \
  add /path/to/storage-root /path/to/ingest/files \
  -u "test" \
  -a "ross@gocfl" \
  -m "open preserve format corpus" \
  --object-id 'rs:dir:{{id}}' \
  --log-level DEBUG
```

It's not 100% clear to me why your version might panic, although if you have modified your config at all, then there's a related issue which is still being triaged: https://github.com/ocfl-archive/gocfl/issues/124

I can cut down my config to the following very minimal version:

```toml
[log]
level = "info"

[Init]
# --ocfl-version
OCFLVersion="1.1"
# --default-storageroot-extensions
#StorageRootExtensions="./data/defaultextensions/storageroot"
# --digest
Digest="sha512"

[Add]
# --message
Message="initial commit"
# --digest
Digest="sha512"
# --fixity
Fixity=["sha256", "sha1", "md5"]
# --default-object-extensions
#ObjectExtensions="./data/fullextensions/object"

DefaultArea="content"

[Add.User]
# --user-name
Name="unknown user"
# --user-address
Address="https://github.com/ocfl-archive/gocfl"

# Errors if this is desabled.
[Indexer.XML]
Enabled=true
[Indexer.XML.Format.document]
Attributes.xmlns = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml"
Type = "ocr"
Subtype = "FineReader10"
Mime = "application/xml"
```

And when I build the binary again, it won't error, but it will if I remove the `[Indexer.XML]` section. (I have a clearer idea how to fix this now.)

If it still doesn't work with the branch you're in, you can try the develop `dev` branch which I can see is working from a fresh install on my Ubuntu machine.
